[package]
name = "set-date-for-undated-assets"
version = "0.1.0"
edition = "2024"

[dependencies]
argh = { version = "0.1.19", default-features = false }
jiff = { version = "0.2.23", default-features = false }
regex = { version = "1.12.3", default-features = false, features = ["unicode-perl"] }
serde = { version = "1.0.228", default-features = false, features = ["derive"] }
ureq = { version = "3.3.0", default-features = false, features = ["json", "rustls"] }

[dev-dependencies]
serde_json = { version = "1.0.149", default-features = false }
